"""
WordPress Packager Agent
Wraps the generated HTML into a WordPress theme + ZIP archive.
"""
import os
import re
import zipfile


def _slugify_wp(text: str) -> str:
    """Transliterate and slugify for WordPress theme name."""
    _cyr = {
        'а':'a','б':'b','в':'v','г':'g','д':'d','е':'e','ё':'yo','ж':'zh',
        'з':'z','и':'i','й':'y','к':'k','л':'l','м':'m','н':'n','о':'o',
        'п':'p','р':'r','с':'s','т':'t','у':'u','ф':'f','х':'kh','ц':'ts',
        'ч':'ch','ш':'sh','щ':'shch','ъ':'','ы':'y','ь':'','э':'e','ю':'yu','я':'ya',
    }
    result = ''
    for char in text.lower():
        result += _cyr.get(char, char)
    slug = re.sub(r'[^\w\s-]', '', result)
    slug = re.sub(r'[\s_-]+', '-', slug).strip('-')
    return slug or "beauty-master"


def package_wordpress_theme(output_dir: str, html: str, business_info: dict, content: dict):
    """
    Creates a WordPress theme folder and a ZIP archive ready to upload.
    """
    master_name = business_info.get("master_name", "Мастер")
    slug = _slugify_wp(master_name)
    theme_dir = os.path.join(output_dir, "wordpress-theme")
    os.makedirs(theme_dir, exist_ok=True)

    # style.css — WordPress theme header
    style_css = f"""/*
Theme Name: {master_name}
Theme URI:
Author: Generated by Nail Beauty Generator
Description: Nail & beauty master website — dark Science Lab style
Version: 1.0
*/
"""
    with open(os.path.join(theme_dir, "style.css"), "w", encoding="utf-8") as f:
        f.write(style_css)

    # functions.php
    functions_php = """<?php
function beauty_theme_setup() {
    add_theme_support('title-tag');
    add_theme_support('post-thumbnails');
}
add_action('after_setup_theme', 'beauty_theme_setup');

function beauty_theme_scripts() {
    wp_enqueue_style('beauty-style', get_stylesheet_uri());
}
add_action('wp_enqueue_scripts', 'beauty_theme_scripts');
?>
"""
    with open(os.path.join(theme_dir, "functions.php"), "w", encoding="utf-8") as f:
        f.write(functions_php)

    # index.php — wraps the generated HTML
    # Extract just the body content for WordPress template
    body_match = re.search(r'<body[^>]*>(.*?)</body>', html, re.DOTALL)
    body_content = body_match.group(1) if body_match else html

    index_php = f"""<?php get_header(); ?>
{body_content}
<?php get_footer(); ?>
"""
    with open(os.path.join(theme_dir, "index.php"), "w", encoding="utf-8") as f:
        f.write(index_php)

    # header.php
    head_match = re.search(r'<head[^>]*>(.*?)</head>', html, re.DOTALL)
    head_content = head_match.group(1) if head_match else ''
    header_php = f"""<!DOCTYPE html>
<html <?php language_attributes(); ?>>
<head>
<meta charset="<?php bloginfo('charset'); ?>">
<meta name="viewport" content="width=device-width, initial-scale=1">
<?php wp_head(); ?>
{head_content}
</head>
<body <?php body_class(); ?>>
"""
    with open(os.path.join(theme_dir, "header.php"), "w", encoding="utf-8") as f:
        f.write(header_php)

    # footer.php
    footer_php = """<?php wp_footer(); ?>
</body>
</html>
"""
    with open(os.path.join(theme_dir, "footer.php"), "w", encoding="utf-8") as f:
        f.write(footer_php)

    # Create ZIP archive
    zip_path = os.path.join(output_dir, f"{slug}-theme.zip")
    with zipfile.ZipFile(zip_path, 'w', zipfile.ZIP_DEFLATED) as zf:
        for root, dirs, files in os.walk(theme_dir):
            for file in files:
                file_path = os.path.join(root, file)
                arcname = os.path.relpath(file_path, output_dir)
                zf.write(file_path, arcname)
